name: Deploy Chat App 

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CHAT_APP

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CHAT_APP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.CHAT_APP_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.CHAT_APP_USER }}@${{ secrets.CHAT_APP_HOST }} << 'EOF'
            source ~/.nvm/nvm.sh
            cd chat-app-server
            git pull origin master
            npm install
            pm2 restart index
          EOF
